Repository nabilalamgir/soen_341, pull requests merged in 2020-03, with the labels that each got.

#55 Fixed Issue #49 & 50
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/UserPostsController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.edmx
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Details.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Edit.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.Designer.cs.dll
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.cs.dll
Labels: task

#66 Sprint 3 Tasks and Stories
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/.vs/config/applicationhost.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/CommentsController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/HomeController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/UserPostsController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/UsersController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Class1.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Comment.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.Designer.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.edmx
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.edmx.diagram
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/PostAndComments.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/SubNamesAndLatestPost.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/User.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/UserPost.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/SOEN341InstagramReplica.csproj
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/SOEN341InstagramReplica.csproj.user
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Comments/Create.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Comments/Delete.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/SignUp.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Shared/_Layout.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Create.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Delete.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Details.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Details2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Edit.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/Delete.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/Details2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/MySubscriptions.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.Designer.cs.dll
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.cs.dll
  Database.sql
Labels: priority 1

#83 Milansprint4
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/UserPostsController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/LikeDislikeList.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.Context.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.edmx
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.edmx.diagram
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/PostAndComments.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/User.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/UserPost.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/SOEN341InstagramReplica.csproj
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Details2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/Details2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Web.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.Designer.cs.dll
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.cs.dll
  Database.sql
Labels: priority 1

#91 Milansprint4
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica.Tests/App.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Content/PagedList.css
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/HomeController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/SOEN341InstagramReplica.csproj
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Trending.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Trending2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Web.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/packages.config
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.1.17.0.0/.signature.p7s
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.1.17.0.0/PagedList.1.17.0.0.nupkg
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.1.17.0.0/lib/net40/PagedList.dll
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.1.17.0.0/lib/net40/PagedList.xml
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.Mvc.4.5.0.0/.signature.p7s
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.Mvc.4.5.0.0/Content/Content/PagedList.css
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.Mvc.4.5.0.0/PagedList.Mvc.4.5.0.0.nupkg
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.Mvc.4.5.0.0/lib/net40/PagedList.Mvc.XML
  BaseProject#1/SOEN341InstagramReplica/packages/PagedList.Mvc.4.5.0.0/lib/net40/PagedList.Mvc.dll
Labels: priority 1

#93 Added Global Search bar
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/.vs/config/applicationhost.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/HomeController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Index.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Trending.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Shared/_Layout.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Index.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/Index.cshtml
Labels: priority 1

#97 Add Trending Page
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/.vs/config/applicationhost.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/HomeController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/SOEN341InstagramReplica.csproj
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Search.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Trending.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Shared/_Layout.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
Labels: enhancement, task

#103 Milansprint4
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/.vs/config/applicationhost.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/HomeController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/LinkedAccountsController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/UserPostsController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Controllers/UsersController.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/FavouritesList.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/LinkedAccount.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.Context.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.edmx
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/Model1.edmx.diagram
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/PostAndComments.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/User.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/UserAndPosts.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Models/UserPost.cs
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/SOEN341InstagramReplica.csproj
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/SOEN341InstagramReplica.csproj.user
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/LinkedAccounts/Delete.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Shared/_Layout.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/UserPosts/Details2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/Details2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/LinkAccount.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/MyFavourites.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Web.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/images/favourite.png
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/images/unfavourite.png
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/DesignTimeResolveAssemblyReferencesInput.cache
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.Designer.cs.dll
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Debug/TempPE/Models.Model1.cs.dll
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Release/DesignTimeResolveAssemblyReferencesInput.cache
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/obj/Release/SOEN341InstagramReplica.csprojAssemblyReference.cache
  Database.sql
Labels: priority 1

#104 Fix Password on Login and SignUp Page + Fix Grammar Mistake
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/.suo
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-shm
  BaseProject#1/SOEN341InstagramReplica/.vs/SOEN341InstagramReplica/v15/Server/sqlite3/storage.ide-wal
  BaseProject#1/SOEN341InstagramReplica/.vs/config/applicationhost.config
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Comments/Create.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Index.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Login.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Search.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/SignUp.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Home/Trending.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/Details2.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/MyFavourites.cshtml
  BaseProject#1/SOEN341InstagramReplica/SOEN341InstagramReplica/Views/Users/MySubscriptions.cshtml
Labels: task
